### ISSUE TITLE
Probleme das er nicht immer mehr Startet

### ISSUE THREAD

**Issue by xXWAZORXx** [DrTraxx/Leitstellenspiel#11]
Habe das Problem das dein Skript in letzter zeit nicht immer geht, die Felder zum auswählen sind weg und kommen nicht, auch nicht nach mehrfachen aktualisieren.

Bei der "normalen" und der "Polizei" Version getestet.

Browser habe ich Chrome, Opera und Edge getestet überall der gleiche Fehler.

Gruß Chris

**Comment by DrTraxx** [comment]
Es gab ein Datenbank-Problem im Rename-Manager. Mit der v 1.4.4 ist das behoben.
Vielen Dank für deine Fehlermeldung.
